const axios = require("axios");

const PROJECT_ID = "7tu1ayj5";
const DATASET = "production";
const API_VERSION = "v2021-06-07";
const TOKEN = process.env.SANITY_WRITE_TOKEN;

const API_URL = `https://${PROJECT_ID}.api.sanity.io/${API_VERSION}/data/mutate/${DATASET}`;

const products = [
  {
    name: "MacBook Pro 16 M2 Pro",
    price: 2499,
    discount: 10,
    brand: "apple",
    category: ["digital", "laptop"],
    isOffer: true,
    starRating: 5,
    slug: "macbook-pro-16-m2-pro",
    registerDate: "2026-05-01T00:00:00.000Z",
    details: {
      processor: "Apple M2 Pro (12-core CPU, 19-core GPU)",
      screen: "16.2 inch Liquid Retina XDR",
      ram: "32GB Unified Memory",
      ssd: "1TB SSD",
      ports: "3x Thunderbolt 4, HDMI, SDXC, MagSafe 3",
      graphic: "19-core GPU",
      warranty: "1 Year",
      operating_system: "macOS Ventura",
    },
  },
  {
    name: "Samsung Galaxy S25 Ultra",
    price: 1299,
    discount: 5,
    brand: "samsung",
    category: ["digital", "mobile"],
    isOffer: true,
    starRating: 5,
    slug: "samsung-galaxy-s25-ultra",
    registerDate: "2026-05-02T00:00:00.000Z",
    details: {
      processor: "Snapdragon 8 Gen 4",
      screen: "6.9 inch Dynamic AMOLED 2X",
      ram: "16GB",
      ssd: "512GB",
      battery: "5000mAh",
      back_camera: "200MP + 50MP + 12MP + 10MP",
      front_camera: "12MP",
      operating_system: "Android 15, One UI 7",
      warranty: "1 Year",
    },
  },
  {
    name: "Sony WH-1000XM6 Wireless Headphones",
    price: 349,
    discount: 15,
    brand: "sony",
    category: ["digital", "headphones"],
    isOffer: true,
    starRating: 5,
    slug: "sony-wh-1000xm6-headphones",
    registerDate: "2026-05-03T00:00:00.000Z",
    details: {
      frequency_response: "4Hz-40,000Hz",
      bluetooth: true,
      noise_cancelling: true,
      microphone: true,
      wireless: true,
      wireless_standby_time: "40 hours",
      connectionType: ["Bluetooth 5.3", "3.5mm"],
      connectors: ["USB-C"],
      warranty: "2 Years",
    },
  },
  {
    name: "Asus ROG Zephyrus G16",
    price: 1999,
    discount: 8,
    brand: "asus",
    category: ["digital", "laptop"],
    isOffer: true,
    starRating: 4,
    slug: "asus-rog-zephyrus-g16",
    registerDate: "2026-05-04T00:00:00.000Z",
    details: {
      processor: "Intel Core Ultra 9 285H",
      screen: "16 inch QHD+ 240Hz OLED",
      ram: "32GB DDR5",
      ssd: "1TB NVMe SSD",
      graphic: "NVIDIA RTX 4070 8GB",
      ports: "2x USB-C, 2x USB-A, HDMI 2.1, RJ45",
      warranty: "2 Years",
      operating_system: "Windows 11 Pro",
    },
  },
  {
    name: "iPhone 16 Pro Max",
    price: 1499,
    brand: "apple",
    category: ["digital", "mobile"],
    isOffer: true,
    starRating: 5,
    slug: "iphone-16-pro-max",
    registerDate: "2026-05-05T00:00:00.000Z",
    details: {
      processor: "A18 Pro Chip",
      screen: "6.9 inch Super Retina XDR OLED",
      ram: "8GB",
      ssd: "256GB",
      battery: "4685mAh",
      back_camera: "48MP + 48MP + 12MP",
      front_camera: "12MP",
      operating_system: "iOS 20",
      warranty: "1 Year",
    },
  },
  {
    name: "Dell XPS 15 OLED",
    price: 1799,
    brand: "del",
    category: ["digital", "laptop"],
    isOffer: false,
    starRating: 4,
    slug: "dell-xps-15-oled",
    registerDate: "2026-05-06T00:00:00.000Z",
    details: {
      processor: "Intel Core Ultra 7 265H",
      screen: "15.6 inch 3.5K OLED Touch",
      ram: "16GB DDR5",
      ssd: "512GB NVMe SSD",
      graphic: "Intel Arc Graphics",
      ports: "3x USB-C Thunderbolt 4, microSD",
      warranty: "1 Year",
      operating_system: "Windows 11 Home",
    },
  },
  {
    name: "Samsung 49 Odyssey G9 Curved Monitor",
    price: 1399,
    discount: 20,
    brand: "samsung",
    category: ["digital", "computer", "monitor"],
    isOffer: true,
    starRating: 5,
    slug: "samsung-odyssey-g9-49-curved-monitor",
    registerDate: "2026-05-07T00:00:00.000Z",
    details: {
      screen: "49 inch Dual QHD",
      resolution: "5120 x 1440",
      display_type: "QLED",
      viewing_angle: "178/178",
      response_time: "1ms",
      refresh_rate: "240Hz",
      panel_technology: "VA",
      input_output_types: "DisplayPort 1.4, HDMI 2.1, USB-C",
      curved: true,
      built_in_speakers: true,
      warranty: "2 Years",
    },
  },
  {
    name: "LG UltraFine 32UN880-B 4K Monitor",
    price: 699,
    brand: "lg",
    category: ["digital", "computer", "monitor"],
    isOffer: false,
    starRating: 4,
    slug: "lg-ultrafine-32un880-b-4k-monitor",
    registerDate: "2026-05-08T00:00:00.000Z",
    details: {
      screen: "32 inch 4K UHD",
      resolution: "3840 x 2160",
      display_type: "IPS",
      viewing_angle: "178/178",
      response_time: "5ms",
      refresh_rate: "60Hz",
      panel_technology: "IPS",
      input_output_types: "USB-C (96W PD), 2x HDMI, DisplayPort",
      curved: false,
      built_in_speakers: true,
      warranty: "3 Years",
    },
  },
  {
    name: "Nike Air Max 270 React",
    price: 149,
    discount: 25,
    brand: "adidas",
    category: ["fashion", "shoes"],
    isOffer: true,
    starRating: 4,
    slug: "nike-air-max-270-react",
    registerDate: "2026-05-09T00:00:00.000Z",
  },
  {
    name: "Gucci Leather Shoulder Bag",
    price: 2190,
    brand: "gucci",
    category: ["fashion", "women"],
    isOffer: false,
    starRating: 5,
    slug: "gucci-leather-shoulder-bag",
    registerDate: "2026-05-10T00:00:00.000Z",
  },
  {
    name: "Puma Running Shoes Ultra 5",
    price: 119,
    discount: 30,
    brand: "puma",
    category: ["fashion", "shoes", "sport"],
    isOffer: true,
    starRating: 4,
    slug: "puma-running-shoes-ultra-5",
    registerDate: "2026-05-11T00:00:00.000Z",
  },
  {
    name: "Dior Sauvage Eau de Parfum 100ml",
    price: 135,
    brand: "dior",
    category: ["beauty", "cosmetic"],
    isOffer: false,
    starRating: 5,
    slug: "dior-sauvage-edp-100ml",
    registerDate: "2026-05-12T00:00:00.000Z",
  },
  {
    name: "L'Oreal Paris Revitalift Serum",
    price: 32,
    discount: 15,
    brand: "loreal",
    category: ["beauty", "cosmetic"],
    isOffer: true,
    starRating: 4,
    slug: "loreal-revitalift-serum",
    registerDate: "2026-05-13T00:00:00.000Z",
  },
  {
    name: "Versace Eros Flame 50ml",
    price: 89,
    brand: "versace",
    category: ["beauty", "cosmetic"],
    isOffer: false,
    starRating: 4,
    slug: "versace-eros-flame-50ml",
    registerDate: "2026-05-14T00:00:00.000Z",
  },
  {
    name: "Rolex Submariner Date",
    price: 12999,
    brand: "rolex",
    category: ["fashion", "watch"],
    isOffer: false,
    starRating: 5,
    slug: "rolex-submariner-date",
    registerDate: "2026-05-15T00:00:00.000Z",
  },
  {
    name: "Patek Philippe Nautilus 5711",
    price: 34999,
    brand: "patek-philippe",
    category: ["fashion", "watch"],
    isOffer: false,
    starRating: 5,
    slug: "patek-philippe-nautilus-5711",
    registerDate: "2026-05-16T00:00:00.000Z",
  },
  {
    name: "Louis Vuitton Neverfull MM Tote",
    price: 1560,
    brand: "louis-vuitton",
    category: ["fashion", "women"],
    isOffer: true,
    starRating: 5,
    slug: "louis-vuitton-neverfull-mm-tote",
    registerDate: "2026-05-17T00:00:00.000Z",
  },
  {
    name: "Bose QuietComfort Ultra Earbuds",
    price: 299,
    discount: 12,
    brand: "sony",
    category: ["digital", "headphones"],
    isOffer: true,
    starRating: 4,
    slug: "bose-quietcomfort-ultra-earbuds",
    registerDate: "2026-05-18T00:00:00.000Z",
    details: {
      bluetooth: true,
      noise_cancelling: true,
      microphone: true,
      wireless: true,
      wireless_standby_time: "6 hours",
      connectionType: ["Bluetooth 5.3"],
      frequency_response: "20Hz-20,000Hz",
      sound_isolating: true,
      warranty: "1 Year",
    },
  },
  {
    name: "Dyson V15 Detect Cordless Vacuum",
    price: 749,
    discount: 10,
    brand: "lg",
    category: ["home"],
    isOffer: true,
    starRating: 5,
    slug: "dyson-v15-detect-cordless-vacuum",
    registerDate: "2026-05-19T00:00:00.000Z",
  },
  {
    name: "KitchenAid Artisan Stand Mixer",
    price: 449,
    brand: "lg",
    category: ["home"],
    isOffer: false,
    starRating: 4,
    slug: "kitchenaid-artisan-stand-mixer",
    registerDate: "2026-05-20T00:00:00.000Z",
  },
  {
    name: "LEGO Star Wars Millennium Falcon",
    price: 849,
    discount: 5,
    brand: "sony",
    category: ["toys"],
    isOffer: true,
    starRating: 5,
    slug: "lego-star-wars-millennium-falcon",
    registerDate: "2026-05-21T00:00:00.000Z",
  },
  {
    name: "Moleskine Classic Notebook Hard Cover",
    price: 19,
    brand: "mac",
    category: ["stationery"],
    isOffer: false,
    starRating: 4,
    slug: "moleskine-classic-notebook-hard-cover",
    registerDate: "2026-05-22T00:00:00.000Z",
  },
  {
    name: "Faber-Castell 36 Color Pencil Set",
    price: 39,
    discount: 20,
    brand: "mac",
    category: ["stationery", "toys"],
    isOffer: true,
    starRating: 4,
    slug: "faber-castell-36-color-pencil-set",
    registerDate: "2026-05-23T00:00:00.000Z",
  },
  {
    name: "Adidas Originals Stan Smith",
    price: 89,
    discount: 10,
    brand: "adidas",
    category: ["fashion", "men", "shoes"],
    isOffer: true,
    starRating: 4,
    slug: "adidas-originals-stan-smith",
    registerDate: "2026-05-24T00:00:00.000Z",
  },
  {
    name: "Xiaomi Mi Smart Band 8 Pro",
    price: 69,
    brand: "xiaomi",
    category: ["digital", "mobile"],
    isOffer: false,
    starRating: 4,
    slug: "xiaomi-mi-smart-band-8-pro",
    registerDate: "2026-05-25T00:00:00.000Z",
    details: {
      screen: "1.74 inch AMOLED",
      battery: "14 days",
      bluetooth: true,
      wireless: true,
      warranty: "1 Year",
    },
  },
  {
    name: "BenQ PD3220U Designer Monitor",
    price: 1199,
    brand: "benq",
    category: ["digital", "computer", "monitor"],
    isOffer: false,
    starRating: 4,
    slug: "benq-pd3220u-designer-monitor",
    registerDate: "2026-05-26T00:00:00.000Z",
    details: {
      screen: "32 inch 4K UHD",
      resolution: "3840 x 2160",
      display_type: "IPS",
      viewing_angle: "178/178",
      response_time: "5ms",
      refresh_rate: "60Hz",
      panel_technology: "IPS",
      input_output_types: "USB-C (85W PD), HDMI, DisplayPort",
      built_in_speakers: true,
      warranty: "3 Years",
    },
  },
  {
    name: "Maybelline Super Stay Foundation",
    price: 14,
    brand: "maybelline",
    category: ["beauty"],
    isOffer: false,
    starRating: 4,
    slug: "maybelline-super-stay-foundation",
    registerDate: "2026-05-27T00:00:00.000Z",
  },
  {
    name: "BVLGARI Omnia Crystalline 40ml",
    price: 72,
    brand: "bvlgari",
    category: ["beauty", "cosmetic"],
    isOffer: false,
    starRating: 4,
    slug: "bvlgari-omnia-crystalline-40ml",
    registerDate: "2026-05-28T00:00:00.000Z",
  },
  {
    name: "Dolce & Gabbana Light Blue 50ml",
    price: 85,
    discount: 10,
    brand: "dolce-gabbana",
    category: ["beauty", "cosmetic"],
    isOffer: true,
    starRating: 5,
    slug: "dolce-gabbana-light-blue-50ml",
    registerDate: "2026-05-29T00:00:00.000Z",
  },
  {
    name: "Adidas Adizero Adios Pro 3 Running Shoes",
    price: 219,
    discount: 15,
    brand: "adidas",
    category: ["fashion", "shoes", "sport"],
    isOffer: true,
    starRating: 5,
    slug: "adidas-adizero-adios-pro-3",
    registerDate: "2026-05-30T00:00:00.000Z",
  },
  {
    name: "Sony PlayStation 5 Pro",
    price: 699,
    discount: 5,
    brand: "sony",
    category: ["digital", "toys"],
    isOffer: true,
    starRating: 5,
    slug: "sony-playstation-5-pro",
    registerDate: "2026-06-01T00:00:00.000Z",
    details: {
      processor: "Custom AMD Zen 2 8-core",
      graphic: "Custom AMD RDNA 3.5 16GB",
      ssd: "2TB NVMe SSD",
      ports: "3x USB-C, 1x USB-A, HDMI 2.1",
      warranty: "1 Year",
    },
  },
  {
    name: "MSI Stealth 14 Studio Gaming Laptop",
    price: 1899,
    brand: "msi",
    category: ["digital", "laptop"],
    isOffer: false,
    starRating: 4,
    slug: "msi-stealth-14-studio-gaming-laptop",
    registerDate: "2026-06-02T00:00:00.000Z",
    details: {
      processor: "Intel Core i9-13900H",
      screen: "14 inch QHD+ 240Hz",
      ram: "32GB DDR5",
      ssd: "1TB NVMe SSD",
      graphic: "NVIDIA RTX 4070 8GB",
      ports: "1x Thunderbolt 4, 2x USB-C, 1x HDMI",
      warranty: "2 Years",
      operating_system: "Windows 11 Home",
    },
  },
  {
    name: "HP Spectre x360 16 2-in-1",
    price: 1599,
    discount: 10,
    brand: "hp",
    category: ["digital", "laptop"],
    isOffer: true,
    starRating: 4,
    slug: "hp-spectre-x360-16-2-in-1",
    registerDate: "2026-06-03T00:00:00.000Z",
    details: {
      processor: "Intel Core Ultra 7 155H",
      screen: "16 inch 3K+ OLED Touch",
      ram: "16GB LPDDR5x",
      ssd: "512GB NVMe SSD",
      graphic: "Intel Arc Graphics",
      ports: "2x Thunderbolt 4, 1x USB-A, HDMI 2.1",
      warranty: "1 Year",
      operating_system: "Windows 11 Home",
    },
  },
  {
    name: "Toshiba 55-inch 4K Smart TV",
    price: 549,
    brand: "toshiba",
    category: ["digital", "home"],
    isOffer: false,
    starRating: 4,
    slug: "toshiba-55-inch-4k-smart-tv",
    registerDate: "2026-06-04T00:00:00.000Z",
    details: {
      screen: "55 inch 4K UHD",
      resolution: "3840 x 2160",
      display_type: "LED",
      refresh_rate: "60Hz",
      built_in_speakers: true,
      warranty: "2 Years",
    },
  },
];

async function seed() {
  if (!TOKEN) {
    console.error("Error: SANITY_WRITE_TOKEN environment variable is not set.");
    console.error("Run: $env:SANITY_WRITE_TOKEN='your-token-here'");
    process.exit(1);
  }

  const mutations = products.map((p) => ({
    create: {
      _type: "product",
      image: [],
      name: p.name,
      slug: { _type: "slug", current: p.slug },
      price: p.price,
      discount: p.discount || 0,
      details: p.details || {},
      brand: p.brand,
      category: p.category,
      isOffer: p.isOffer || false,
      registerDate: p.registerDate,
      starRating: p.starRating || 0,
    },
  }));

  console.log(`Seeding ${mutations.length} products to Sanity...`);

  try {
    const { data } = await axios.post(
      API_URL,
      { mutations },
      {
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${TOKEN}`,
        },
      }
    );
    const created = data.results.length;
    console.log(`Success: ${created}/${mutations.length} products created.`);
  } catch (err) {
    if (err.response) {
      console.error("API Error:", JSON.stringify(err.response.data, null, 2));
    } else {
      console.error("Error:", err.message);
    }
    process.exit(1);
  }
}

seed();
